services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York # set this to your own desired timezone
    volumes:
      - /path/to/overseerr/config:/config # Change this to your desired path
    ports:
      - 5055:5055
    restart: unless-stopped
