services:
  cloudflare_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: river_styx # Change to the name of your choosing
    environment:
      - TZ=America/New_York # set this to your own desired timezone
    volumes:
      - ./cloudflared/data:/home/nonroot/.cloudflared/ # Change this to your desired path
    command: tunnel run --token ${TUNNEL_TOKEN} # ${TUNNEL_TOKEN} should come from a .env file with the format of 'TUNNEL_TOKEN=_some_token_value_'
    network_mode: host
    restart: unless-stopped
