services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York # set this to your own desired timezone
    volumes:
      - /path/to/data:/config # Change this to your desired path
      - /path/to/tvseries:/tv # Change this to your desired path
      - /path/to/downloadclient-downloads:/downloads # Change this to your desired path
      - /path/to/backups:/var/backups # Change this to your desired path; optional but recommended to restore your Radarr data later
    ports:
      - 8989:8989
    restart: unless-stopped
