services:
###############  Media-Streaming Containers  ################
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM} # has to be PLEX_CLAIM; value is set in .env file alongside compose file; .env file should be in format of VARIABLE="STRING"
      - PLEX_GID=${PGID:-1000}
      - PLEX_UID=${PUID:-1000}
      - UMASK_SET=022
      - ADVERTISE_IP=${ADVERTISE_IP} # has to be ADVERTISE_IP; value is set in .env file alongside compose file; .env file should be in format of VARIABLE="STRING"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./plex/config:/config
      - ./data/media/movies:/data/movies
      - ./data/media/tv:/data/tv
      - /tmp:/transcode # Have transcoding happen in RAM
    devices:
      - /dev/dri/:/dev/dri/ # For hardware acceleration/transcoding
      
# TODO: Consider adding Jellyfin or Kodi or Emby as an alternative to Plex

###############  Media-Management Containers  ################
  bazarr: # For subtitle management
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    # ports:
    #   - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bazarr:/config
      - ./data/media/movies:/data/media/movies
      - ./data/media/tv:/data/media/tv

  radarr: # For movie management
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    # ports:
    #   - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config
      - ./data/media/movies:/media/movies
      - ./qbittorent/downloads:/downloads

  sonarr: # For TV show management
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    # ports:
    #   - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr:/config
      - ./data/media/tv:/media/tv
      - ./qbittorent/downloads:/downloads
# Todo: Look into adding Overseer container for requests

###############  Media-fetching Containers  ################
  jackett: 
      image: lscr.io/linuxserver/jackett:latest
      container_name: jackett
      restart: unless-stopped
      network_mode: host
      logging:
        driver: "json-file"
        options:
          max-size: "100m"
          max-file: "10"
      environment:
        - PUID=1000
        - PGID=1000
        - AUTO_UPDATE=true 
        # - RUN_OPTS= #optional
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./jackett:/config
        - ./qbittorent/downloads:/downloads
      # ports:
      #   - 9117:9117

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      - PUID=1000
      - PGID=1000 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/appdata/overseerr:/config
      - ./data:/data

# TODO: look into adding a qbit container for torrenting

