services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York # set this to your own desired timezone
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /path/to/data:/config # Change this to your desired path
      - /path/to/blackhole:/downloads # Change this to your desired path
    ports:
      - 9117:9117
    restart: unless-stopped
