services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York # set this to your own desired timezone
    volumes:
      - /path/to/radarr/data:/config
      - /path/to/movies:/movies # Change this to your desired path
      - /path/to/download-client-downloads:/downloads # Change this to your desired path
      - /path/to/backups:/var/backups # Change this to your desired path; optional but recommended to restore your Radarr data later
    ports:
      - 7878:7878
    restart: unless-stopped
