version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      # substitute your value for {some_dir_ex_myMovies} for where your movies are kept
      - {some_dir_ex_myMovies}:/movies
      # substitute your value for {some_dir_ex_myShows} for where your movies are kept
      - {some_dir_ex_myShows}:/shows
    ports:
      - 6767:6767
    restart: unless-stopped
