services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York # set this to your own desired timezone
      - VERSION=docker
      - PLEX_CLAIM={PLEX_CLAIM}
      - UMASK_SET=022
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/shows # Change this to your desired path
      - /path/to/movies:/movies # Change this to your desired path
      - /dev/shm:/transcode # This is optional and uses RAM to speed up transcoding
      - /path/to/Library/Application Support/Plex Media Server:/data # All data Plex uses and generates (e.g. watch history) lives here
    devices:
     - /dev/dri:/dev/dri
    restart: unless-stopped
