# This includes Plex and containers to support Plex (e.g. Sonarr or Bazarr) as well as a Cloudflare tunnel for remote access
services:
###############  Media-managment Containers  ################
  bazarr: # For subtitles
      image: lscr.io/linuxserver/bazarr:latest
      container_name: bazarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York # set this to your own desired timezone
      volumes:
        - /path/to/bazarr/config:/config # Set this
        - /path/to/movies:/movies # Set this (optional but recommended in most cases)
        - /path/to/tv:/tv # Set this (optional but recommended in most cases)
      ports:
        - 6767:6767
      restart: unless-stopped
  
  overseerr: # For media requests and issues
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York # set this to your own desired timezone
    volumes:
      - /path/to/overseerr/config:/config # Change this to your desired path
    ports:
      - 5055:5055
    restart: unless-stopped

  radarr: # For movie management
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York # set this to your own desired timezone
    volumes:
      - /path/to/radarr/data:/config
      - /path/to/movies:/movies # Change this to your desired path
      - /path/to/download-client-downloads:/downloads # Change this to your desired path
      - /path/to/backups:/var/backups # Change this to your desired path; optional but recommended to restore your Radarr data later
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York # set this to your own desired timezone
    volumes:
      - /path/to/data:/config # Change this to your desired path
      - /path/to/tvseries:/tv # Change this to your desired path
      - /path/to/downloadclient-downloads:/downloads # Change this to your desired path
      - /path/to/backups:/var/backups # Change this to your desired path; optional but recommended to restore your Radarr data later
    ports:
      - 8989:8989
    restart: unless-stopped

###############  Networking-management  ################
  cloudflare_tunnel: # For remote access
      image: cloudflare/cloudflared:latest
      container_name: river_styx # Change to the name of your choosing
      environment:
        - TZ=America/New_York # set this to your own desired timezone
      volumes:
        - ./cloudflared/data:/home/nonroot/.cloudflared/ # Change this to your desired path
      command: tunnel run --token ${TUNNEL_TOKEN} # ${TUNNEL_TOKEN} should come from a .env file with the format of 'TUNNEL_TOKEN=_some_token_value_'
      network_mode: host
      restart: unless-stopped

###############  Media-fetching Containers  ################
  jackett: # For torrent/indexer searching
      image: lscr.io/linuxserver/jackett:latest
      container_name: jackett
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York # set this to your own desired timezone
        - AUTO_UPDATE=true #optional
        - RUN_OPTS= #optional
      volumes:
        - /path/to/data:/config # Change this to your desired path
        - /path/to/blackhole:/downloads # Change this to your desired path
      ports:
        - 9117:9117
      restart: unless-stopped

###############  Media-Streaming Containers  ################
  plex:
      image: lscr.io/linuxserver/plex:latest
      container_name: plex
      network_mode: host
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York # set this to your own desired timezone
        - VERSION=docker
        - PLEX_CLAIM={PLEX_CLAIM}
        - UMASK_SET=022
      volumes:
        - /path/to/library:/config
        - /path/to/tvseries:/shows # Change this to your desired path
        - /path/to/movies:/movies # Change this to your desired path
        - /dev/shm:/transcode # This is optional and uses RAM to speed up transcoding
        - ./path/to/Library/Application Support/Plex Media Server:/data # All data Plex uses and generates (e.g. watch history) lives here
      devices:
      - /dev/dri:/dev/dri
      restart: unless-stopped
      
  # TODO: Consider adding Jellyfin or Kodi or Emby as an alternative to Plex

